# Generated by Django 2.0.4 on 2018-04-16 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(blank=True, choices=[('Control', 'Control'), ('Perform', 'Perform')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('department', models.TextField(choices=[('ТЦЭС', 'ТЦЭС'), ('ПЦЭС', 'ПЦЭС'), ('КЦЭС', 'КЦЭС'), ('СЦЭС', 'СЦЭС')])),
                ('check_period', models.IntegerField(choices=[(1, '1'), (3, '3'), (6, '6'), (12, '12')])),
                ('last_success_check_date', models.DateField(default=None, null=True)),
                ('next_check_date', models.DateField()),
                ('status', models.TextField(choices=[('Актуально', 'Актуально'), ('В работе', 'В работе'), ('Неактуально', 'Неактуально'), ('На доработке', 'На доработке'), ('На проверке', 'На проверке')], default='Неактуально')),
                ('document_file', models.FileField(default=None, upload_to='')),
            ],
        ),
    ]
