# Generated by Django 2.0.4 on 2018-04-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0002_remove_document_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
