# Generated by Django 2.0.4 on 2018-04-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0003_auto_20180422_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='BaseUser',
        ),
    ]
